---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-patcho
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-patcho
rules:
- apiGroups: [""]
  resources: [configmaps]
  verbs: [create,get,update,patch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-update-binding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-patcho
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-patcho